### ISSUE TITLE
User menu not working

### ISSUE THREAD

**Issue by vasyl-shumskyi** [sipcapture/homer-ui#16]
Hey,

Looks like user menu is not working, except logout button. Tried with Chrome and FF
Can you verify it on your end to omit false alarm?

<img width="482" alt="screen shot 2015-07-09 at 23 09 33" src="https://cloud.githubusercontent.com/assets/2331802/8605735/f09183b2-268f-11e5-9bd9-1c984c1ff3fa.png">

Thanks!

**Comment by lmangani** [comment]
Hi Vasyl, those are placeholders for upcoming functionality while in Beta

**Comment by vasyl-shumskyi** [comment]
Thanks. Got it :)

**Comment by michaelarnauts** [comment]
Shouldn't this issue be kept open until the issue is resolved, just to keep track of the open issues?

**Comment by lmangani** [comment]
Since this is scheduled/queued for removal, and unless anyone has intentions to fill those links sooner than later I believe this being not an "issue" rather a placeholder clarification but we can keep it open for tracking until gone.

**Comment by michaelarnauts** [comment]
It might make sense for a user to be able to change his or her password (under profile). I don't know about the other items (settings, notifications and messages). I think that even reset profile doesn't make any sense anymore, since AFAIK the profile is kept in session, and logging out destroys it.
