### ISSUE TITLE
IPV6 combining by aliases in subnets, different scenarios.

### ISSUE THREAD

**Issue by jacovinus** [sipcapture/homer-ui#298]
*Interesting question for the Homer community!*

Looking for suggestions on displaying combined aliases in an IPV6 subnet on flow (real and most usual cases) on different scenarios. 

@systemcrash, may you start with some use cases?

**Comment by systemcrash** [comment]
The problem here (when matching IPs as strings) is sub-strings within strings (at least that was the case for IPv4) e.g.:
192.168.1.1 is found within 192.168.1.11 and so on. If IPs are strings, expect these problems. 

It is difficult to imagine all of the scenarios where this problem might manifest in the IPv6 address space. 

This problem will manifest in IPv6 in the following scenarios e.g.
fdee:f9b:d2c2:3044::1
fdee:f9b:d2c2:3044::1:192.168.1.1
(ipv4 address within IPv6)


fdee:f9b:d2c2:3044::1
fdee:f9b:d2c2:3044::1001


::1
::1000

The assumption here is if it is 'prefix' matching. In which case these will collide, if they are not [] encapsulated.
::1234:5678
::1234:5678:9abc


This is the inherent property of using string based matching. If the IPs are converted to integers (use an IP library), then everything will be fine. 

Was this what you were asking?

**Comment by systemcrash** [comment]
( There are times where we use aliases for IPv6, yes. Although we have not yet experienced any collisions. )

**Comment by systemcrash** [comment]
In light of this comment ( https://github.com/sipcapture/homer-app/issues/310#issuecomment-647776957 ), is the 'mask' field in aliases, the subnet netmask? What bearing or effect should 'mask' have?

If I try to set 32 to 24 for a 24 bit subnet, I don't see any effect currently for IPv4. 


Masks probably have no effect on strings - but IP handling libraries are wise to this.

**Comment by jacovinus** [comment]
@systemcrash We already took a look at different libraries to solve that issue and are taking actually a different path to solve it ;).

**Comment by adubovikov** [comment]
please reopen if needed
